// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameActorAdmin = "actor_admin"

// ActorAdmin mapped from table <actor_admin>
type ActorAdmin struct {
	CreatedAt    int64  `gorm:"column:created_at" json:"created_at"`
	CreatedBy    string `gorm:"column:created_by" json:"created_by"`
	ModifiedAt   int64  `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy   string `gorm:"column:modified_by" json:"modified_by"`
	DeletedAt    int64  `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy    string `gorm:"column:deleted_by" json:"deleted_by"`
	ActorAdminID string `gorm:"column:actor_admin_id;primaryKey" json:"actor_admin_id"`
	ActorName    string `gorm:"column:actor_name;not null" json:"actor_name"`
	Email        string `gorm:"column:email;not null" json:"email"`
	Msisdn       string `gorm:"column:msisdn;not null" json:"msisdn"`
	Password     string `gorm:"column:password;not null" json:"password"`
	RoleID       string `gorm:"column:role_id;not null" json:"role_id"`
	MerchantID   string `gorm:"column:merchant_id" json:"merchant_id"`
	IsActive     bool   `gorm:"column:is_active" json:"is_active"`
}

// TableName ActorAdmin's table name
func (*ActorAdmin) TableName() string {
	return TableNameActorAdmin
}
