// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCart = "cart"

// Cart mapped from table <cart>
type Cart struct {
	CartID     int64  `gorm:"column:cart_id;primaryKey;autoIncrement:true" json:"cart_id"`
	CustomerID string `gorm:"column:customer_id;not null" json:"customer_id"`
	LocationID string `gorm:"column:location_id;not null" json:"location_id"`
	OutletID   string `gorm:"column:outlet_id;not null" json:"outlet_id"`
	CreatedAt  int64  `gorm:"column:created_at" json:"created_at"`
	CreatedBy  string `gorm:"column:created_by" json:"created_by"`
	ModifiedAt int64  `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy string `gorm:"column:modified_by" json:"modified_by"`
	DeletedAt  int64  `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy  string `gorm:"column:deleted_by" json:"deleted_by"`
}

// TableName Cart's table name
func (*Cart) TableName() string {
	return TableNameCart
}
