// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChannel = "channel"

// Channel mapped from table <channel>
type Channel struct {
	CreatedAt   int64  `gorm:"column:created_at" json:"created_at"`
	CreatedBy   string `gorm:"column:created_by" json:"created_by"`
	ModifiedAt  int64  `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy  string `gorm:"column:modified_by" json:"modified_by"`
	DeletedAt   int64  `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy   string `gorm:"column:deleted_by" json:"deleted_by"`
	ChannelID   string `gorm:"column:channel_id;primaryKey" json:"channel_id"`
	ChannelCode string `gorm:"column:channel_code;not null" json:"channel_code"`
	ChannelName string `gorm:"column:channel_name;not null" json:"channel_name"`
	SortOrder   int32  `gorm:"column:sort_order" json:"sort_order"`
	URLIcon     string `gorm:"column:url_icon;not null" json:"url_icon"`
}

// TableName Channel's table name
func (*Channel) TableName() string {
	return TableNameChannel
}
