// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomer = "customer"

// Customer mapped from table <customer>
type Customer struct {
	CreatedAt   int64  `gorm:"column:created_at" json:"created_at"`
	CreatedBy   string `gorm:"column:created_by" json:"created_by"`
	ModifiedAt  int64  `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy  string `gorm:"column:modified_by" json:"modified_by"`
	DeletedAt   int64  `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy   string `gorm:"column:deleted_by" json:"deleted_by"`
	CustomerID  string `gorm:"column:customer_id;primaryKey;default:gen_random_uuid()" json:"customer_id"`
	Name        string `gorm:"column:name" json:"name"`
	Email       string `gorm:"column:email" json:"email"`
	Msisdn      string `gorm:"column:msisdn;not null" json:"msisdn"`
	Password    string `gorm:"column:password" json:"password"`
	URLHeadPic  string `gorm:"column:url_head_pic" json:"url_head_pic"`
	IsActive    bool   `gorm:"column:is_active;default:true" json:"is_active"`
	IsTsel      bool   `gorm:"column:is_tsel" json:"is_tsel"`
	TselNotifID string `gorm:"column:tsel_notif_id" json:"tsel_notif_id"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
