// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataEnv = "data_env"

// DataEnv mapped from table <data_env>
type DataEnv struct {
	EnvID     int32  `gorm:"column:env_id;primaryKey;autoIncrement:true" json:"env_id"`
	EnvGroup  string `gorm:"column:env_group;not null" json:"env_group"`
	ParentID  int32  `gorm:"column:parent_id" json:"parent_id"`
	EnvName   string `gorm:"column:env_name;not null" json:"env_name"`
	EnvValue  string `gorm:"column:env_value;not null" json:"env_value"`
	SortOrder int32  `gorm:"column:sort_order" json:"sort_order"`
}

// TableName DataEnv's table name
func (*DataEnv) TableName() string {
	return TableNameDataEnv
}
