// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameInboxCustomer = "inbox_customer"

// InboxCustomer mapped from table <inbox_customer>
type InboxCustomer struct {
	InboxCustomerID string `gorm:"column:inbox_customer_id;primaryKey" json:"inbox_customer_id"`
	CustomerID      string `gorm:"column:customer_id;not null" json:"customer_id"`
	InboxID         string `gorm:"column:inbox_id;not null" json:"inbox_id"`
}

// TableName InboxCustomer's table name
func (*InboxCustomer) TableName() string {
	return TableNameInboxCustomer
}
