// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLocationCode = "location_code"

// LocationCode mapped from table <location_code>
type LocationCode struct {
	LocationID string    `gorm:"column:location_id;primaryKey" json:"location_id"`
	Timestamp  time.Time `gorm:"column:timestamp;primaryKey" json:"timestamp"`
	SeqCode    int32     `gorm:"column:seq_code;not null" json:"seq_code"`
}

// TableName LocationCode's table name
func (*LocationCode) TableName() string {
	return TableNameLocationCode
}
