// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMenuStock = "menu_stock"

// MenuStock mapped from table <menu_stock>
type MenuStock struct {
	CreatedAt    int64  `gorm:"column:created_at" json:"created_at"`
	CreatedBy    string `gorm:"column:created_by" json:"created_by"`
	ModifiedAt   int64  `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy   string `gorm:"column:modified_by" json:"modified_by"`
	DeletedAt    int64  `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy    string `gorm:"column:deleted_by" json:"deleted_by"`
	MenuStockID  int64  `gorm:"column:menu_stock_id;primaryKey;autoIncrement:true" json:"menu_stock_id"`
	OutletMenuID string `gorm:"column:outlet_menu_id;not null" json:"outlet_menu_id"`
	IsAvailable  bool   `gorm:"column:is_available;not null;default:true" json:"is_available"`
}

// TableName MenuStock's table name
func (*MenuStock) TableName() string {
	return TableNameMenuStock
}
