// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMenuFavorite = "menu_favorite"

// MenuFavorite mapped from table <menu_favorite>
type MenuFavorite struct {
	CreatedAt      int64  `gorm:"column:created_at" json:"created_at"`
	CreatedBy      string `gorm:"column:created_by" json:"created_by"`
	ModifiedAt     int64  `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy     string `gorm:"column:modified_by" json:"modified_by"`
	DeletedAt      int64  `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy      string `gorm:"column:deleted_by" json:"deleted_by"`
	MenuFavoriteID string `gorm:"column:menu_favorite_id;primaryKey" json:"menu_favorite_id"`
	OutletMenuID   string `gorm:"column:outlet_menu_id;not null" json:"outlet_menu_id"`
	CustomerID     string `gorm:"column:customer_id;not null" json:"customer_id"`
}

// TableName MenuFavorite's table name
func (*MenuFavorite) TableName() string {
	return TableNameMenuFavorite
}
