// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMerchantKyc = "merchant_kyc"

// MerchantKyc mapped from table <merchant_kyc>
type MerchantKyc struct {
	MerchantKycID string `gorm:"column:merchant_kyc_id;primaryKey" json:"merchant_kyc_id"`
	MerchantID    string `gorm:"column:merchant_id;not null" json:"merchant_id"`
	IdentityNo    string `gorm:"column:identity_no;not null" json:"identity_no"`
	BirthPlace    string `gorm:"column:birth_place;not null" json:"birth_place"`
	Dob           string `gorm:"column:dob;not null" json:"dob"`
	Address       string `gorm:"column:address;not null" json:"address"`
	URLIdentity   string `gorm:"column:url_identity;not null" json:"url_identity"`
	URLSelfie     string `gorm:"column:url_selfie;not null" json:"url_selfie"`
}

// TableName MerchantKyc's table name
func (*MerchantKyc) TableName() string {
	return TableNameMerchantKyc
}
