// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNavigation = "navigation"

// Navigation mapped from table <navigation>
type Navigation struct {
	CreatedAt          int64  `gorm:"column:created_at" json:"created_at"`
	CreatedBy          string `gorm:"column:created_by" json:"created_by"`
	ModifiedAt         int64  `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy         string `gorm:"column:modified_by" json:"modified_by"`
	DeletedAt          int64  `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy          string `gorm:"column:deleted_by" json:"deleted_by"`
	NavigationID       string `gorm:"column:navigation_id;primaryKey" json:"navigation_id"`
	NavigationName     string `gorm:"column:navigation_name;not null" json:"navigation_name"`
	ParentNavigationID string `gorm:"column:parent_navigation_id" json:"parent_navigation_id"`
	SortOrder          int32  `gorm:"column:sort_order;not null" json:"sort_order"`
	URLPath            string `gorm:"column:url_path" json:"url_path"`
	IsActive           bool   `gorm:"column:is_active;default:true" json:"is_active"`
	IsPermission       bool   `gorm:"column:is_permission" json:"is_permission"`
}

// TableName Navigation's table name
func (*Navigation) TableName() string {
	return TableNameNavigation
}
