// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	OrderID     string `gorm:"column:order_id;primaryKey" json:"order_id"`
	CustomerID  string `gorm:"column:customer_id;not null" json:"customer_id"`
	OutletID    string `gorm:"column:outlet_id;not null" json:"outlet_id"`
	OrderedAt   int64  `gorm:"column:ordered_at;not null" json:"ordered_at"`
	OrderStatus string `gorm:"column:order_status;not null;comment:PENDING|SUBMITTED|ON_PROCESS|COMPLETED" json:"order_status"` // PENDING|SUBMITTED|ON_PROCESS|COMPLETED
	ServingType string `gorm:"column:serving_type;not null;comment:PICKUP|DINE_IN" json:"serving_type"`                         // PICKUP|DINE_IN
	ExpiredAt   int64  `gorm:"column:expired_at;not null" json:"expired_at"`
	DisplayName string `gorm:"column:display_name" json:"display_name"`
	DeletedAt   int64  `gorm:"column:deleted_at" json:"deleted_at"`
	ModifiedAt  int64  `gorm:"column:modified_at" json:"modified_at"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
