// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrderItem = "order_item"

// OrderItem mapped from table <order_item>
type OrderItem struct {
	OrderItemID  string  `gorm:"column:order_item_id;primaryKey" json:"order_item_id"`
	OrderID      string  `gorm:"column:order_id;not null" json:"order_id"`
	OutletMenuID string  `gorm:"column:outlet_menu_id;not null" json:"outlet_menu_id"`
	MenuName     string  `gorm:"column:menu_name;not null" json:"menu_name"`
	Description  string  `gorm:"column:description" json:"description"`
	URLImage     string  `gorm:"column:url_image" json:"url_image"`
	Price        float64 `gorm:"column:price;not null" json:"price"`
	Qty          int32   `gorm:"column:qty;not null" json:"qty"`
	Notes        string  `gorm:"column:notes" json:"notes"`
}

// TableName OrderItem's table name
func (*OrderItem) TableName() string {
	return TableNameOrderItem
}
