// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrderRefund = "order_refunds"

// OrderRefund mapped from table <order_refunds>
type OrderRefund struct {
	CreatedAt     int32   `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt     int32   `gorm:"column:updated_at" json:"updated_at"`
	RefundID      string  `gorm:"column:refund_id;primaryKey" json:"refund_id"`
	OrderID       string  `gorm:"column:order_id;not null" json:"order_id"`
	MerchantID    string  `gorm:"column:merchant_id;not null" json:"merchant_id"`
	AccountBank   string  `gorm:"column:account_bank;not null" json:"account_bank"`
	AccountName   string  `gorm:"column:account_name;not null" json:"account_name"`
	AccountNumber string  `gorm:"column:account_number;not null" json:"account_number"`
	RefundAmount  float64 `gorm:"column:refund_amount;not null" json:"refund_amount"`
	RefundReason  string  `gorm:"column:refund_reason" json:"refund_reason"`
	RefundStatus  string  `gorm:"column:refund_status" json:"refund_status"`
}

// TableName OrderRefund's table name
func (*OrderRefund) TableName() string {
	return TableNameOrderRefund
}
