// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrderRating = "order_rating"

// OrderRating mapped from table <order_rating>
type OrderRating struct {
	OrderRatingID string `gorm:"column:order_rating_id;primaryKey" json:"order_rating_id"`
	OrderID       string `gorm:"column:order_id;not null" json:"order_id"`
	Rating        int32  `gorm:"column:rating;not null" json:"rating"`
	ReviewAt      int64  `gorm:"column:review_at;not null" json:"review_at"`
	ReviewMsg     string `gorm:"column:review_msg" json:"review_msg"`
	ReplyAt       int64  `gorm:"column:reply_at" json:"reply_at"`
	ReplyBy       string `gorm:"column:reply_by" json:"reply_by"`
	ReplyMsg      string `gorm:"column:reply_msg" json:"reply_msg"`
	IsAnonymous   bool   `gorm:"column:is_anonymous" json:"is_anonymous"`
}

// TableName OrderRating's table name
func (*OrderRating) TableName() string {
	return TableNameOrderRating
}
