// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOutletCuisine = "outlet_cuisine"

// OutletCuisine mapped from table <outlet_cuisine>
type OutletCuisine struct {
	CreatedAt       int64  `gorm:"column:created_at" json:"created_at"`
	CreatedBy       string `gorm:"column:created_by" json:"created_by"`
	ModifiedAt      int64  `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy      string `gorm:"column:modified_by" json:"modified_by"`
	DeletedAt       int64  `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy       string `gorm:"column:deleted_by" json:"deleted_by"`
	OutletCuisineID string `gorm:"column:outlet_cuisine_id;primaryKey" json:"outlet_cuisine_id"`
	OutletID        string `gorm:"column:outlet_id;not null" json:"outlet_id"`
	CuisineID       string `gorm:"column:cuisine_id;not null" json:"cuisine_id"`
}

// TableName OutletCuisine's table name
func (*OutletCuisine) TableName() string {
	return TableNameOutletCuisine
}
