// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOutletSection = "outlet_section"

// OutletSection mapped from table <outlet_section>
type OutletSection struct {
	CreatedAt       int64  `gorm:"column:created_at" json:"created_at"`
	CreatedBy       string `gorm:"column:created_by" json:"created_by"`
	ModifiedAt      int64  `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy      string `gorm:"column:modified_by" json:"modified_by"`
	DeletedAt       int64  `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy       string `gorm:"column:deleted_by" json:"deleted_by"`
	OutletSectionID string `gorm:"column:outlet_section_id;primaryKey" json:"outlet_section_id"`
	OutletID        string `gorm:"column:outlet_id;not null" json:"outlet_id"`
	SectionName     string `gorm:"column:section_name;not null" json:"section_name"`
	IsActive        bool   `gorm:"column:is_active;not null;default:true" json:"is_active"`
}

// TableName OutletSection's table name
func (*OutletSection) TableName() string {
	return TableNameOutletSection
}
