// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOutletFavorite = "outlet_favorite"

// OutletFavorite mapped from table <outlet_favorite>
type OutletFavorite struct {
	CreatedAt        int64  `gorm:"column:created_at" json:"created_at"`
	CreatedBy        string `gorm:"column:created_by" json:"created_by"`
	ModifiedAt       int64  `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy       string `gorm:"column:modified_by" json:"modified_by"`
	DeletedAt        int64  `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy        string `gorm:"column:deleted_by" json:"deleted_by"`
	OutletFavoriteID string `gorm:"column:outlet_favorite_id;primaryKey;default:gen_random_uuid()" json:"outlet_favorite_id"`
	OutletID         string `gorm:"column:outlet_id;not null" json:"outlet_id"`
	CustomerID       string `gorm:"column:customer_id;not null" json:"customer_id"`
}

// TableName OutletFavorite's table name
func (*OutletFavorite) TableName() string {
	return TableNameOutletFavorite
}
