// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOutletSectionMenu = "outlet_section_menu"

// OutletSectionMenu mapped from table <outlet_section_menu>
type OutletSectionMenu struct {
	CreatedAt       int64  `gorm:"column:created_at" json:"created_at"`
	CreatedBy       string `gorm:"column:created_by" json:"created_by"`
	OutletSmID      int64  `gorm:"column:outlet_sm_id;primaryKey;autoIncrement:true" json:"outlet_sm_id"`
	OutletSectionID string `gorm:"column:outlet_section_id;not null" json:"outlet_section_id"`
	OutletMenuID    string `gorm:"column:outlet_menu_id;not null" json:"outlet_menu_id"`
}

// TableName OutletSectionMenu's table name
func (*OutletSectionMenu) TableName() string {
	return TableNameOutletSectionMenu
}
