// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOutletOp = "outlet_op"

// OutletOp mapped from table <outlet_op>
type OutletOp struct {
	CreatedAt  int64  `gorm:"column:created_at" json:"created_at"`
	CreatedBy  string `gorm:"column:created_by" json:"created_by"`
	ModifiedAt int64  `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy string `gorm:"column:modified_by" json:"modified_by"`
	DeletedAt  int64  `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy  string `gorm:"column:deleted_by" json:"deleted_by"`
	OutletOpID string `gorm:"column:outlet_op_id;primaryKey" json:"outlet_op_id"`
	OutletID   string `gorm:"column:outlet_id;not null" json:"outlet_id"`
	OpenDay    string `gorm:"column:open_day;not null" json:"open_day"`
	OpenHour   string `gorm:"column:open_hour" json:"open_hour"`
	CloseHour  string `gorm:"column:close_hour" json:"close_hour"`
	IsOpen     bool   `gorm:"column:is_open;not null;default:true" json:"is_open"`
}

// TableName OutletOp's table name
func (*OutletOp) TableName() string {
	return TableNameOutletOp
}
