// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOutlet = "outlet"

// Outlet mapped from table <outlet>
type Outlet struct {
	CreatedAt       int64   `gorm:"column:created_at" json:"created_at"`
	CreatedBy       string  `gorm:"column:created_by" json:"created_by"`
	ModifiedAt      int64   `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy      string  `gorm:"column:modified_by" json:"modified_by"`
	DeletedAt       int64   `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy       string  `gorm:"column:deleted_by" json:"deleted_by"`
	OutletID        string  `gorm:"column:outlet_id;primaryKey" json:"outlet_id"`
	MerchantID      string  `gorm:"column:merchant_id;not null" json:"merchant_id"`
	OutletName      string  `gorm:"column:outlet_name;not null" json:"outlet_name"`
	Phone           string  `gorm:"column:phone;not null" json:"phone"`
	LocationID      string  `gorm:"column:location_id;not null" json:"location_id"`
	URLMain         string  `gorm:"column:url_main;not null" json:"url_main"`
	URLCover        string  `gorm:"column:url_cover;not null" json:"url_cover"`
	IsActive        bool    `gorm:"column:is_active;not null" json:"is_active"`
	Rating          float64 `gorm:"column:rating" json:"rating"`
	TotalRating     int32   `gorm:"column:total_rating" json:"total_rating"`
	IsOpen          bool    `gorm:"column:is_open;not null" json:"is_open"`
	Tag             string  `gorm:"column:tag" json:"tag"`
	TotalRatingUser int32   `gorm:"column:total_rating_user" json:"total_rating_user"`
	IsAlert         bool    `gorm:"column:is_alert;default:true" json:"is_alert"`
}

// TableName Outlet's table name
func (*Outlet) TableName() string {
	return TableNameOutlet
}
