// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOutletLogName = "outlet_log_name"

// OutletLogName mapped from table <outlet_log_name>
type OutletLogName struct {
	ModifiedAt      int64  `gorm:"column:modified_at;not null" json:"modified_at"`
	ModifiedBy      string `gorm:"column:modified_by;not null" json:"modified_by"`
	OutletLogNameID int64  `gorm:"column:outlet_log_name_id;primaryKey;autoIncrement:true" json:"outlet_log_name_id"`
	OutletID        string `gorm:"column:outlet_id;not null" json:"outlet_id"`
	OutletName      string `gorm:"column:outlet_name;not null" json:"outlet_name"`
}

// TableName OutletLogName's table name
func (*OutletLogName) TableName() string {
	return TableNameOutletLogName
}
