// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOutletQri = "outlet_qris"

// OutletQri mapped from table <outlet_qris>
type OutletQri struct {
	CreatedAt    int64  `gorm:"column:created_at" json:"created_at"`
	CreatedBy    string `gorm:"column:created_by" json:"created_by"`
	ModifiedAt   int64  `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy   string `gorm:"column:modified_by" json:"modified_by"`
	DeletedAt    int64  `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy    string `gorm:"column:deleted_by" json:"deleted_by"`
	OutletQrisID int32  `gorm:"column:outlet_qris_id;primaryKey;autoIncrement:true" json:"outlet_qris_id"`
	OutletID     string `gorm:"column:outlet_id;not null" json:"outlet_id"`
	Nmid         string `gorm:"column:nmid;not null" json:"nmid"`
	QrisCode     string `gorm:"column:qris_code;not null" json:"qris_code"`
}

// TableName OutletQri's table name
func (*OutletQri) TableName() string {
	return TableNameOutletQri
}
