// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePayment = "payment"

// Payment mapped from table <payment>
type Payment struct {
	PaymentID   string  `gorm:"column:payment_id;primaryKey" json:"payment_id"`
	OrderID     string  `gorm:"column:order_id;not null" json:"order_id"`
	ChannelID   string  `gorm:"column:channel_id;not null" json:"channel_id"`
	Amount      float64 `gorm:"column:amount;not null" json:"amount"`
	UniqueCode  int32   `gorm:"column:unique_code;not null" json:"unique_code"`
	PickupFee   float64 `gorm:"column:pickup_fee;not null" json:"pickup_fee"`
	ServiceFee  float64 `gorm:"column:service_fee;not null" json:"service_fee"`
	Vat         float64 `gorm:"column:vat;not null" json:"vat"`
	URLProof    string  `gorm:"column:url_proof" json:"url_proof"`
	ReferenceID string  `gorm:"column:reference_id" json:"reference_id"`
}

// TableName Payment's table name
func (*Payment) TableName() string {
	return TableNamePayment
}
