// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	CreatedAt  int64  `gorm:"column:created_at" json:"created_at"`
	CreatedBy  string `gorm:"column:created_by" json:"created_by"`
	ModifiedAt int64  `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy string `gorm:"column:modified_by" json:"modified_by"`
	DeletedAt  int64  `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy  string `gorm:"column:deleted_by" json:"deleted_by"`
	RoleID     string `gorm:"column:role_id;primaryKey" json:"role_id"`
	RoleName   string `gorm:"column:role_name;not null" json:"role_name"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
