// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserEvent = "user_event"

// UserEvent mapped from table <user_event>
type UserEvent struct {
	ActorEventID string `gorm:"column:actor_event_id;primaryKey" json:"actor_event_id"`
	CustomerID   string `gorm:"column:customer_id" json:"customer_id"`
	MerchantID   string `gorm:"column:merchant_id" json:"merchant_id"`
	EventName    string `gorm:"column:event_name;not null" json:"event_name"`
	SecretCode   string `gorm:"column:secret_code;not null" json:"secret_code"`
	ExpiredAt    int64  `gorm:"column:expired_at;not null" json:"expired_at"`
}

// TableName UserEvent's table name
func (*UserEvent) TableName() string {
	return TableNameUserEvent
}
